### PR TITLE
:gift: Buoy will float to branch for submodules other then root

### LINKED ISSUE #36: Buoy support for nested submodules without named tags
### Important note

In a nutshell any potential improvement can't break existing repositories and update workflows due to unnecessary maintenance burden to fix  other repos because of 1 requirement. 

### Per comment on the 1.17 release issue

The current floating and updating of knative deps doesn't work well with `client` and `client/pkg` (sort of submodule that doesn't have submodule tag create on the client repo). There's the following error whenever resolving to `knative.dev/client` package only. This error may hinder bumps for other dependencies (to further investigated).

```
  go: module knative.dev/client@v0.44.0 found, but does not contain package knative.dev/client/pkg

```

https://github.com/knative-extensions/knobots/actions/runs/12987687379/job/36217114020#step:6:399

In this example there's resolution for both `client` and `client/pkg`, but ideally we should limit the path crawling to the latter only and skip `knative.dev/client` completely.
```
Floating deps to knative.dev/client-pkg@release-1.17 knative.dev/client/pkg@v0.44.0 knative.dev/eventing-kafka-broker@v0.44.0 knative.dev/hack@release-1.17 knative.dev/pkg@release-1.17

```

A few example of different flag combinations. Ideally for the case of `knative.dev/client/pkg` we would only need to resolve to release branch. That's offered in `--ruleset Branch`. However, the default flag combination and workflows for other repos would not benefit from it. 

The other discussed option is to alter `buoy` resolution for packages nested deeper than repository root level. That sounds ideal for `client/pkg` use case.

```
➜  kn-plugin-event git:(main) buoy float ./go.mod -d knative.dev/client --release 1.17 --module-release 0.44 --ruleset Branch
knative.dev/client/pkg@release-1.17
➜  kn-plugin-event git:(main) buoy float ./go.mod -d knative.dev/client --release 1.17
knative.dev/client/pkg@release-1.17
➜  kn-plugin-event git:(main) buoy float ./go.mod -d knative.dev/client --release 1.17 --module-release 0.44
knative.dev/client/pkg@v0.44.0
```

### PR DESCRIPTION
**Pull request by cardil**
**Which issue(s) this PR fixes**:<br>
Fixes #36

### CODE REVIEW

**Comment by cardil** [comment]
/cc @dsimansk 

I think this is it. Please, take a look.

**Review by dsimansk — CHANGES_REQUESTED** [review]
Would you mind capturing a note in README.md and also adding a bit of context to the `float` cmd help message, pls?

**Comment by dsimansk** [comment]
Otherwise works well in a few tries I've done on main Serving and plugins repos. It really does what we need with recognizing submodule. :)

File: pkg/git/git_test.go [hunk 1]
```diff
@@ -83,6 +86,13 @@ func TestRepo_BestRefFor(t *testing.T) {
 			release: ReleaseRef,
 			rule:    AnyRule,
 		},
+		"Any - v0.2 - with submodule": {
+			repo:    submoduleRepo,
+			version: semver.MustParse("0.2.0"),
+			want:    "ref@release-0.2",
```
Comment (n3wscott) [inline pkg/git/git_test.go:92]: I think this should be `ref@sub/release-0.2` no? is this not a tag? perhaps this is a branch and I don't fully understand what the goal is.

Comment (cardil) [reply pkg/git/git_test.go:92]: We thought to go for the branches for submodules. Otherwise, we would need to add additional Git tags to the repo like: `sub/v0.2.0`.

In fact, in that case we wouldn't need to adjust the buoy, as the `ref@v0.2.0` will just work, if those additional tags were added to the repo.

**Review by dsimansk — APPROVED** [review]
